### ISSUE TITLE
Obfusca apk working on kotlin?

### ISSUE THREAD

**Issue by sickoxyz** [ClaudiuGeorgiu/Obfuscapk#170] opened 2023-09-07 03:42 UTC
hi, the obfuscapk working on kotlin ???

**Comment by ClaudiuGeorgiu** [comment] 2023-09-07 10:20
Closing as duplicate of https://github.com/ClaudiuGeorgiu/Obfuscapk/issues/34.

**Closed by ClaudiuGeorgiu** 2023-09-07 10:20 UTC
Labels: question
